# App Config
spring.application.name=backend
server.port=9990

# Postgres Config
spring.datasource.url=jdbc:postgresql://localhost:5432/stocktrum_db
spring.datasource.username=tonyha
spring.datasource.password=1234
# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hikari Config
logging.level.org.hibernate.orm.connections.pooling= WARN